name: Login WeChat Developer Tools

description: >
  Login WeChat Developer Tools in the CI environment so that projects can be correctly loaded via CLI.

branding:
  icon: user
  color: green

inputs:
  smtp-host:
    description: SMTP server to send Login QR Code
  smtp-port:
    description: SMTP port to send Login QR Code
  smtp-secure:
    description: Whether SMTPS is used
    default: false
  smtp-username:
    description: SMTP username to login the mail server
  smtp-password:
    description: SMTP password to login the mail server
  smtp-sender:
    description: Email address of the sender
  smtp-receiver:
    description: Email address of the receiver

runs:
  using: node12
  pre: install.js
  main: dist/index.js
