name: Node.js CI

on:
  push:
    branches:
      - canary
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    strategy:
      matrix:
        node-version: [14.x]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm ci, build, and test
      run: |
        npm ci
        npm run build
        node .github/workflows/check-dist.js
        npm test

  setup:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install WeChat Developer Tools
      uses: takashiro/setup-wechat-devtools@v1

    - name: Checkout project
      uses: actions/checkout@v2
      with:
        repository: takashiro/bezier-werewolf-wechat
        ref: 6ec326a685d806be88a6b02716580fae37976555
        path: test-project

    - name: Build project
      run: |
        npm ci
        npm run build
      working-directory: test-project

    - name: Login WeChat Developer Tools
      uses: ./
      with:
        smtp-host: ${{ secrets.SMTP_HOST }}
        smtp-port: ${{ secrets.SMTP_HOST }}
        smtp-username: ${{ secrets.SMTP_USERNAME }}
        smtp-password: ${{ secrets.SMTP_PASSWORD }}
        smtp-sender: ${{ secrets.SMTP_SENDER }}

    - name: Build NPM
      run: wxdev build-npm --project=${{ github.workspace }}/test-project

    - name: Load project
      run: wxdev auto --project=${{ github.workspace }}/test-project --auto-port=8888

    - name: Run end-to-end tests
      run: npx jest --config=test/e2e/jest.config.js LobbyPage.spec.ts
      working-directory: test-project
